project:
  type: website

execute:
  freeze: auto

website:
  title: "<span class='site-name'>Social Science Sofa | </span> <span class='logo-text'>[___]</span>"
  site-url: https://thesocialsciencesofa.com

  navbar:
    left:
      - href: blog/index.qmd
        text: Blog
      - href: https://r4np.com
        text: R4NP Book
        target: _blank

    right:
      - icon: person-circle
        href: https://danieldauber.com
        target: _blank
      - icon: github
        href: https://github.com/ddauber
        target: _blank
      - icon: twitter-x
        href: https://x.com/daniel_dauber
        target: _blank
      - icon: bluesky
        href: https://bsky.app/profile/danieldauber.bsky.social
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/danieldauber/
        target: _blank
      - icon: rss
        href: index.xml
  description: "The Social Science Sofa is your cosy corner for data visualisation, R programming, and research insights—where complex ideas recline into clarity."
  google-analytics: "G-T3MQH2G66G"

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - favicon.html
      - social.html
    include-before-body: head.html
    include-after-body: after_body.html

resources:
  - favicon/social_card.png